import { UserProfile, Transaction, RiskAlert } from '../../../shared/types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'U1023',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    phone: '+91 98201 45892',
    accountAgeDays: 420,
    historicalAverageAmount: 6500,
    historicalMaxAmount: 18000,
    usualLocation: 'Delhi, India',
    usualDevice: 'DEV889',
    knownDevices: ['DEV889', 'DEV412'],
    knownLocations: ['Delhi, India', 'Noida, India', 'Gurgaon, India'],
    totalTransactionsCount: 142,
    failedTransactionsCountLast30Days: 1,
    riskTier: 'STANDARD',
    createdDate: '2025-06-15T10:00:00Z',
  },
  {
    id: 'U1088',
    name: 'Priya Venkatesh',
    email: 'priya.v@example.com',
    phone: '+91 97412 88390',
    accountAgeDays: 610,
    historicalAverageAmount: 3200,
    historicalMaxAmount: 9500,
    usualLocation: 'Bengaluru, India',
    usualDevice: 'DEV301',
    knownDevices: ['DEV301'],
    knownLocations: ['Bengaluru, India'],
    totalTransactionsCount: 215,
    failedTransactionsCountLast30Days: 0,
    riskTier: 'STANDARD',
    createdDate: '2024-12-10T08:30:00Z',
  },
  {
    id: 'U1145',
    name: 'Rohan Mehta',
    email: 'rohan.mehta@example.com',
    phone: '+91 98210 11994',
    accountAgeDays: 180,
    historicalAverageAmount: 12500,
    historicalMaxAmount: 35000,
    usualLocation: 'Mumbai, India',
    usualDevice: 'DEV552',
    knownDevices: ['DEV552', 'DEV998'],
    knownLocations: ['Mumbai, India', 'Thane, India', 'Pune, India'],
    totalTransactionsCount: 88,
    failedTransactionsCountLast30Days: 3,
    riskTier: 'ELEVATED',
    createdDate: '2026-02-20T14:15:00Z',
  },
  {
    id: 'U2099',
    name: 'Ananya Gupta',
    email: 'ananya.g@example.com',
    phone: '+91 99100 55432',
    accountAgeDays: 2,
    historicalAverageAmount: 1200,
    historicalMaxAmount: 2000,
    usualLocation: 'Kolkata, India',
    usualDevice: 'DEV770',
    knownDevices: ['DEV770'],
    knownLocations: ['Kolkata, India'],
    totalTransactionsCount: 2,
    failedTransactionsCountLast30Days: 4,
    riskTier: 'HIGH_MONITORING',
    createdDate: '2026-08-23T09:00:00Z',
  },
  {
    id: 'U3041',
    name: 'Vikramaditya Rao',
    email: 'vikram.rao@example.com',
    phone: '+91 94480 33219',
    accountAgeDays: 780,
    historicalAverageAmount: 15000,
    historicalMaxAmount: 60000,
    usualLocation: 'Hyderabad, India',
    usualDevice: 'DEV109',
    knownDevices: ['DEV109', 'DEV110'],
    knownLocations: ['Hyderabad, India', 'Secunderabad, India'],
    totalTransactionsCount: 340,
    failedTransactionsCountLast30Days: 0,
    riskTier: 'STANDARD',
    createdDate: '2024-06-01T12:00:00Z',
  },
  {
    id: 'U4012',
    name: 'Sneha Patel',
    email: 'sneha.patel@example.com',
    phone: '+91 98795 66781',
    accountAgeDays: 95,
    historicalAverageAmount: 4500,
    historicalMaxAmount: 12000,
    usualLocation: 'Ahmedabad, India',
    usualDevice: 'DEV618',
    knownDevices: ['DEV618'],
    knownLocations: ['Ahmedabad, India', 'Gandhinagar, India'],
    totalTransactionsCount: 44,
    failedTransactionsCountLast30Days: 2,
    riskTier: 'STANDARD',
    createdDate: '2026-05-20T11:45:00Z',
  },
  {
    id: 'U5120',
    name: 'Kabir Dasgupta',
    email: 'kabir.d@example.com',
    phone: '+91 98300 77412',
    accountAgeDays: 310,
    historicalAverageAmount: 8000,
    historicalMaxAmount: 22000,
    usualLocation: 'Kolkata, India',
    usualDevice: 'DEV811',
    knownDevices: ['DEV811'],
    knownLocations: ['Kolkata, India'],
    totalTransactionsCount: 112,
    failedTransactionsCountLast30Days: 0,
    riskTier: 'STANDARD',
    createdDate: '2025-10-15T15:20:00Z',
  }
];

// Helper to calculate recent ISO timestamps
const now = new Date('2026-08-25T06:00:00Z').getTime();
const minutesAgo = (mins: number) => new Date(now - mins * 60 * 1000).toISOString();
const hoursAgo = (hrs: number) => new Date(now - hrs * 3600 * 1000).toISOString();
const daysAgo = (days: number) => new Date(now - days * 86400 * 1000).toISOString();

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // Scenario E: Multi-Anomaly (The Signature Flagged TXN: TXN10082)
  {
    id: 'TXN10082',
    userId: 'U1023',
    amount: 82500,
    currency: 'INR',
    paymentMethod: 'UPI',
    merchant: 'Electronics Superstore Hub',
    merchantCategory: 'Electronics & High-Risk Goods',
    location: 'Lagos, Nigeria', // Extreme location anomaly
    deviceId: 'DEV999-UNKNOWN', // New device
    deviceType: 'Linux / Chrome 128 (Emulated)',
    ipAddress: '102.89.23.114',
    timestamp: minutesAgo(8),
    status: 'FLAGGED',
  },
  // Velocity batch for U1023 (burst in last 12 minutes)
  {
    id: 'TXN10081',
    userId: 'U1023',
    amount: 45000,
    currency: 'INR',
    paymentMethod: 'UPI',
    merchant: 'Digital Gift Cards Online',
    merchantCategory: 'Digital Goods & Vouchers',
    location: 'Lagos, Nigeria',
    deviceId: 'DEV999-UNKNOWN',
    deviceType: 'Linux / Chrome 128 (Emulated)',
    ipAddress: '102.89.23.114',
    timestamp: minutesAgo(10),
    status: 'FLAGGED',
  },
  {
    id: 'TXN10080',
    userId: 'U1023',
    amount: 25000,
    currency: 'INR',
    paymentMethod: 'UPI',
    merchant: 'Jewelry Mart Direct',
    merchantCategory: 'Jewelry & Luxury',
    location: 'Lagos, Nigeria',
    deviceId: 'DEV999-UNKNOWN',
    deviceType: 'Linux / Chrome 128 (Emulated)',
    ipAddress: '102.89.23.114',
    timestamp: minutesAgo(11),
    status: 'FLAGGED',
  },
  {
    id: 'TXN10079',
    userId: 'U1023',
    amount: 15000,
    currency: 'INR',
    paymentMethod: 'UPI',
    merchant: 'Gaming Credits FastPay',
    merchantCategory: 'Gaming',
    location: 'Lagos, Nigeria',
    deviceId: 'DEV999-UNKNOWN',
    deviceType: 'Linux / Chrome 128 (Emulated)',
    ipAddress: '102.89.23.114',
    timestamp: minutesAgo(12),
    status: 'FLAGGED',
  },
  {
    id: 'TXN10078',
    userId: 'U1023',
    amount: 5000,
    currency: 'INR',
    paymentMethod: 'UPI',
    merchant: 'Quick Pay Crypto Gateway',
    merchantCategory: 'Cryptocurrency Exchange',
    location: 'Lagos, Nigeria',
    deviceId: 'DEV999-UNKNOWN',
    deviceType: 'Linux / Chrome 128 (Emulated)',
    ipAddress: '102.89.23.114',
    timestamp: minutesAgo(13),
    status: 'BLOCKED',
  },

  // Scenario G: New Account with High Value Anomaly (U2099)
  {
    id: 'TXN10077',
    userId: 'U2099',
    amount: 98000,
    currency: 'INR',
    paymentMethod: 'NET_BANKING',
    merchant: 'Bullion Gold Bullion Vault',
    merchantCategory: 'Precious Metals',
    location: 'Dubai, UAE',
    deviceId: 'DEV441-TOR',
    deviceType: 'Unknown Browser / VPN Endpoint',
    ipAddress: '185.220.101.5',
    timestamp: minutesAgo(24),
    status: 'BLOCKED',
  },

  // Scenario B: New Device + Unusual Amount (U1088)
  {
    id: 'TXN10076',
    userId: 'U1088',
    amount: 28500, // 8.9x average
    currency: 'INR',
    paymentMethod: 'CREDIT_CARD',
    merchant: 'Global Luxury Watches',
    merchantCategory: 'Luxury Retail',
    location: 'Bengaluru, India',
    deviceId: 'DEV904-IPHONE', // New device
    deviceType: 'iPhone 15 Pro / Safari',
    ipAddress: '49.37.112.44',
    timestamp: minutesAgo(45),
    status: 'FLAGGED',
  },

  // Scenario C: Location Anomaly (U1145)
  {
    id: 'TXN10075',
    userId: 'U1145',
    amount: 32000,
    currency: 'INR',
    paymentMethod: 'DEBIT_CARD',
    merchant: 'Flight Booking Gateway',
    merchantCategory: 'Travel & Airlines',
    location: 'London, UK', // Usually Mumbai
    deviceId: 'DEV552',
    deviceType: 'Windows 11 / Edge',
    ipAddress: '81.2.69.142',
    timestamp: hoursAgo(1.5),
    status: 'FLAGGED',
  },

  // Scenario D: Velocity Burst on standard user
  {
    id: 'TXN10074',
    userId: 'U4012',
    amount: 14000,
    currency: 'INR',
    paymentMethod: 'UPI',
    merchant: 'Smart Retail Point',
    merchantCategory: 'Retail Goods',
    location: 'Ahmedabad, India',
    deviceId: 'DEV618',
    deviceType: 'Android 14 / Chrome',
    ipAddress: '157.34.88.19',
    timestamp: hoursAgo(2),
    status: 'SUCCESS',
  },
  {
    id: 'TXN10073',
    userId: 'U4012',
    amount: 12500,
    currency: 'INR',
    paymentMethod: 'UPI',
    merchant: 'Smart Retail Point',
    merchantCategory: 'Retail Goods',
    location: 'Ahmedabad, India',
    deviceId: 'DEV618',
    deviceType: 'Android 14 / Chrome',
    ipAddress: '157.34.88.19',
    timestamp: hoursAgo(2.1),
    status: 'SUCCESS',
  },

  // Normal Baseline Transactions (Standard, low risk)
  {
    id: 'TXN10072',
    userId: 'U3041',
    amount: 4500,
    currency: 'INR',
    paymentMethod: 'UPI',
    merchant: 'Supermart Fresh Groceries',
    merchantCategory: 'Supermarkets',
    location: 'Hyderabad, India',
    deviceId: 'DEV109',
    deviceType: 'Pixel 8 / Chrome',
    ipAddress: '106.51.72.190',
    timestamp: hoursAgo(3),
    status: 'SUCCESS',
  },
  {
    id: 'TXN10071',
    userId: 'U1088',
    amount: 1850,
    currency: 'INR',
    paymentMethod: 'UPI',
    merchant: 'Cafe Coffee Roasters',
    merchantCategory: 'Food & Beverage',
    location: 'Bengaluru, India',
    deviceId: 'DEV301',
    deviceType: 'MacBook Pro / Chrome',
    ipAddress: '122.172.88.10',
    timestamp: hoursAgo(4),
    status: 'SUCCESS',
  },
  {
    id: 'TXN10070',
    userId: 'U5120',
    amount: 7200,
    currency: 'INR',
    paymentMethod: 'CREDIT_CARD',
    merchant: 'City Utility Power Bill',
    merchantCategory: 'Utilities',
    location: 'Kolkata, India',
    deviceId: 'DEV811',
    deviceType: 'iPad Air / Safari',
    ipAddress: '115.187.32.9',
    timestamp: hoursAgo(5),
    status: 'SUCCESS',
  },
  {
    id: 'TXN10069',
    userId: 'U1023',
    amount: 4200,
    currency: 'INR',
    paymentMethod: 'UPI',
    merchant: 'Metro Commute Transit',
    merchantCategory: 'Transportation',
    location: 'Delhi, India',
    deviceId: 'DEV889',
    deviceType: 'OnePlus 12 / Chrome',
    ipAddress: '182.72.140.2',
    timestamp: daysAgo(1),
    status: 'SUCCESS',
  },
  {
    id: 'TXN10068',
    userId: 'U1145',
    amount: 11000,
    currency: 'INR',
    paymentMethod: 'CREDIT_CARD',
    merchant: 'Apparel Fashion Mall',
    merchantCategory: 'Clothing & Apparel',
    location: 'Mumbai, India',
    deviceId: 'DEV552',
    deviceType: 'Windows 11 / Edge',
    ipAddress: '49.36.19.22',
    timestamp: daysAgo(1.2),
    status: 'SUCCESS',
  },
  {
    id: 'TXN10067',
    userId: 'U3041',
    amount: 18500,
    currency: 'INR',
    paymentMethod: 'NET_BANKING',
    merchant: 'Home Furnishings Living',
    merchantCategory: 'Home Decor',
    location: 'Hyderabad, India',
    deviceId: 'DEV109',
    deviceType: 'Pixel 8 / Chrome',
    ipAddress: '106.51.72.190',
    timestamp: daysAgo(1.5),
    status: 'SUCCESS',
  },
  {
    id: 'TXN10066',
    userId: 'U5120',
    amount: 6400,
    currency: 'INR',
    paymentMethod: 'UPI',
    merchant: 'HealthPlus Pharmacy',
    merchantCategory: 'Healthcare',
    location: 'Kolkata, India',
    deviceId: 'DEV811',
    deviceType: 'iPad Air / Safari',
    ipAddress: '115.187.32.9',
    timestamp: daysAgo(2),
    status: 'SUCCESS',
  },
  {
    id: 'TXN10065',
    userId: 'U1088',
    amount: 2990,
    currency: 'INR',
    paymentMethod: 'WALLET',
    merchant: 'Bookworm Publishers',
    merchantCategory: 'Books & Education',
    location: 'Bengaluru, India',
    deviceId: 'DEV301',
    deviceType: 'MacBook Pro / Chrome',
    ipAddress: '122.172.88.10',
    timestamp: daysAgo(2.3),
    status: 'SUCCESS',
  },
  {
    id: 'TXN10064',
    userId: 'U1023',
    amount: 8100,
    currency: 'INR',
    paymentMethod: 'UPI',
    merchant: 'Fine Dine Bistro',
    merchantCategory: 'Dining & Restaurants',
    location: 'Delhi, India',
    deviceId: 'DEV889',
    deviceType: 'OnePlus 12 / Chrome',
    ipAddress: '182.72.140.2',
    timestamp: daysAgo(3),
    status: 'SUCCESS',
  },
  {
    id: 'TXN10063',
    userId: 'U4012',
    amount: 3500,
    currency: 'INR',
    paymentMethod: 'UPI',
    merchant: 'Fuel Station Express',
    merchantCategory: 'Automotive & Fuel',
    location: 'Ahmedabad, India',
    deviceId: 'DEV618',
    deviceType: 'Android 14 / Chrome',
    ipAddress: '157.34.88.19',
    timestamp: daysAgo(3.5),
    status: 'SUCCESS',
  }
];

export const INITIAL_ALERTS: RiskAlert[] = [
  {
    id: 'ALT-9001',
    transactionId: 'TXN10082',
    userId: 'U1023',
    type: 'HIGH_RISK_TRANSACTION',
    severity: 'CRITICAL',
    status: 'NEW',
    title: 'Extreme Multi-Factor Anomaly Detected',
    description: 'Transaction amount (₹82,500) is 12.69x historical baseline with simultaneous new device and foreign geolocation (Lagos, Nigeria).',
    riskScore: 88,
    amount: 82500,
    currency: 'INR',
    timestamp: minutesAgo(8),
    assignedTo: 'Senior Risk Analyst (L2)',
  },
  {
    id: 'ALT-9002',
    transactionId: 'TXN10081',
    userId: 'U1023',
    type: 'VELOCITY_ANOMALY',
    severity: 'HIGH',
    status: 'INVESTIGATING',
    title: 'Rapid High-Value Transaction Velocity Burst',
    description: '5 high-value transactions initiated within 5 minutes exceeding total ₹1,72,500 aggregate exposure.',
    riskScore: 84,
    amount: 45000,
    currency: 'INR',
    timestamp: minutesAgo(10),
    assignedTo: 'Automated Fraud Sentry',
  },
  {
    id: 'ALT-9003',
    transactionId: 'TXN10077',
    userId: 'U2099',
    type: 'HIGH_RISK_TRANSACTION',
    severity: 'CRITICAL',
    status: 'NEW',
    title: 'New Account Instant High-Exposure Trigger',
    description: '2-day old account attempted ₹98,000 bullion purchase through VPN/Tor proxy endpoint.',
    riskScore: 92,
    amount: 98000,
    currency: 'INR',
    timestamp: minutesAgo(24),
    assignedTo: 'Tier 1 Risk Desk',
  },
  {
    id: 'ALT-9004',
    transactionId: 'TXN10076',
    userId: 'U1088',
    type: 'UNUSUAL_AMOUNT',
    severity: 'MEDIUM',
    status: 'NEW',
    title: 'Sudden Luxury Spend Deviation on New Device',
    description: 'Transaction amount ₹28,500 is 8.9x average baseline from unverified iPhone 15 Pro hardware.',
    riskScore: 68,
    amount: 28500,
    currency: 'INR',
    timestamp: minutesAgo(45),
  },
  {
    id: 'ALT-9005',
    transactionId: 'TXN10075',
    userId: 'U1145',
    type: 'LOCATION_ANOMALY',
    severity: 'HIGH',
    status: 'INVESTIGATING',
    title: 'Impossible Travel / Foreign Location Deviation',
    description: 'Login and transaction detected in London, UK within 2 hours of Mumbai session.',
    riskScore: 74,
    amount: 32000,
    currency: 'INR',
    timestamp: hoursAgo(1.5),
    assignedTo: 'Fraud Ops Bot',
  }
];
